### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Emeraldhero** [ut-amrl/coda-models#7]
```
  Running setup.py develop for pcdet
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [106 lines of output]
        running develop
        running egg_info
        writing pcdet.egg-info/PKG-INFO
        writing dependency_links to pcdet.egg-info/dependency_links.txt
        writing requirements to pcdet.egg-info/requires.txt
        writing top-level names to pcdet.egg-info/top_level.txt
        reading manifest file 'pcdet.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'pcdet.egg-info/SOURCES.txt'
        running build_ext
        building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
        Emitting ninja build file /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        /home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        [1/1] /home/max/anaconda3/envs/coda11_3/bin/nvcc  -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/coda11_3/include -I/home/max/anaconda3/envs/coda11_3/include/python3.8 -c -c /home/max/Desktop/coda-models/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
        FAILED: /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o
        /home/max/anaconda3/envs/coda11_3/bin/nvcc  -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/coda11_3/include -I/home/max/anaconda3/envs/coda11_3/include/python3.8 -c -c /home/max/Desktop/coda-models/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
        In file included from /home/max/anaconda3/envs/coda11_3/include/cuda_runtime.h:83,
                         from <command-line>:
        /home/max/anaconda3/envs/coda11_3/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
          139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
              |  ^~~~~
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
            subprocess.run(
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/subprocess.py", line 516, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/max/Desktop/coda-models/setup.py", line 34, in <module>
            setup(
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
            self.run_command('build_ext')
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
            _build_ext.run(self)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
            self.build_extensions()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
            build_ext.build_extensions(self)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
            self._build_extensions_serial()
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
            self.build_extension(ext)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
            _build_ext.build_extension(self, ext)
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
            objects = self.compiler.compile(
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 556, in unix_wrap_ninja_compile
            _write_ninja_file_and_compile_objects(
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
            _run_ninja_build(
          File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
            raise RuntimeError(message) from e
        RuntimeError: Error compiling objects for extension
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [106 lines of output]
    running develop
    running egg_info
    writing pcdet.egg-info/PKG-INFO
    writing dependency_links to pcdet.egg-info/dependency_links.txt
    writing requirements to pcdet.egg-info/requires.txt
    writing top-level names to pcdet.egg-info/top_level.txt
    reading manifest file 'pcdet.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'pcdet.egg-info/SOURCES.txt'
    running build_ext
    building 'pcdet.ops.iou3d_nms.iou3d_nms_cuda' extension
    Emitting ninja build file /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    [1/1] /home/max/anaconda3/envs/coda11_3/bin/nvcc  -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/coda11_3/include -I/home/max/anaconda3/envs/coda11_3/include/python3.8 -c -c /home/max/Desktop/coda-models/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    FAILED: /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o
    /home/max/anaconda3/envs/coda11_3/bin/nvcc  -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/TH -I/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/include/THC -I/home/max/anaconda3/envs/coda11_3/include -I/home/max/anaconda3/envs/coda11_3/include/python3.8 -c -c /home/max/Desktop/coda-models/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.cu -o /home/max/Desktop/coda-models/build/temp.linux-x86_64-cpython-38/pcdet/ops/iou3d_nms/src/iou3d_nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
    In file included from /home/max/anaconda3/envs/coda11_3/include/cuda_runtime.h:83,
                     from <command-line>:
    /home/max/anaconda3/envs/coda11_3/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
          |  ^~~~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
        subprocess.run(
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/max/Desktop/coda-models/setup.py", line 34, in <module>
        setup(
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
        build_ext.build_extensions(self)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
        objects = self.compiler.compile(
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 556, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1399, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/max/anaconda3/envs/coda11_3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I get the above error whenever i try to run the `setup.py develop` file. I use the command `pip install -e .` to develop instead of the traditional command provided in the **readme**. I have followed all the other instructions as per the file and am stuck with this problem. 
I am using Ubuntu 22.04 for the above function

**Comment by artzha** [comment]
Hi @Emeraldhero, Thank you for your interest in CODa! It looks like this issue occurs because of an incompatible gcc version. What gcc version are you using in your conda environment and have you tried downgrading to a GCC version earlier than 10?
